-- MySQL Script generated by MySQL Workbench
-- Wed Jan 17 19:03:59 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema XPTO
-- -----------------------------------------------------
-- Banco de dados relacionais do sistema XPTO que gerencia clientes, contas bancárias e suas movimentações.

-- -----------------------------------------------------
-- Schema XPTO
--
-- Banco de dados relacionais do sistema XPTO que gerencia clientes, contas bancárias e suas movimentações.
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `XPTO` DEFAULT CHARACTER SET utf8 COLLATE utf8_bin ;
USE `XPTO` ;

-- -----------------------------------------------------
-- Table `XPTO`.`CLIENTE`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `XPTO`.`CLIENTE` (
  `idCliente` VARCHAR(14) NOT NULL,
  `nome` VARCHAR(45) NOT NULL,
  `telefone` VARCHAR(13) NOT NULL,
  `email` VARCHAR(30) NOT NULL,
  `tipoPessoa` INT NOT NULL,
  PRIMARY KEY (`idCliente`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `XPTO`.`ENDERECO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `XPTO`.`ENDERECO` (
  `idEndereco` INT NOT NULL AUTO_INCREMENT,
  `idCliente` VARCHAR(14) NOT NULL,
  `logradouro` VARCHAR(45) NOT NULL,
  `cep` VARCHAR(8) NOT NULL,
  `cidade` VARCHAR(30) NOT NULL,
  `estado` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`idEndereco`),
  INDEX `fk_ENDERECO_CLIENTE_idx` (`idCliente` ASC) INVISIBLE,
  CONSTRAINT `fk_ENDERECO_CLIENTE`
    FOREIGN KEY (`idCliente`)
    REFERENCES `XPTO`.`CLIENTE` (`idCliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `XPTO`.`CONTA`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `XPTO`.`CONTA` (
  `idConta` INT NOT NULL AUTO_INCREMENT,
  `idCliente` VARCHAR(14) NOT NULL,
  `nomeCliente` VARCHAR(45) NOT NULL,
  `agencia` INT NOT NULL,
  `conta` INT NOT NULL,
  `saldoInicial` DECIMAL(2) NOT NULL,
  `saldoAtual` DECIMAL(2) NOT NULL,
  `movimentaçoesCredito` INT NOT NULL,
  `movimentacoesDebito` INT NOT NULL,
  `dataAbertura` DATE NOT NULL,
  PRIMARY KEY (`idConta`),
  INDEX `fk_CONTA_CLIENTE1_idx` (`idCliente` ASC) INVISIBLE,
  CONSTRAINT `fk_CONTA_CLIENTE1`
    FOREIGN KEY (`idCliente`)
    REFERENCES `XPTO`.`CLIENTE` (`idCliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
